# Generated by Django 6.0.1 on 2026-01-16 17:32

import django.db.models.deletion
import spaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SHOP_S', 'Shop - Small'), ('SHOP_M', 'Shop - Medium'), ('SHOP_L', 'Shop - Large'), ('ATRIUM_NW', 'Atrium - North & West'), ('ATRIUM_S', 'Atrium - South'), ('CINEMA', 'Cinema Theater'), ('MARKETING', 'Marketing Banners')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=spaces.models.getFilename)),
                ('description', models.TextField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=spaces.models.getFilename)),
                ('description', models.TextField()),
                ('duration_type', models.CharField(choices=[('Week Days', 'Week Days'), ('Week Ends', 'Week Ends'), ('Public Holidays', 'Public Holidays'), ('All Days', 'All Days')], max_length=50)),
                ('rent_type', models.CharField(choices=[('Day Wise', 'Day Wise'), ('Hour Wise', 'Hour Wise'), ('Week Wise', 'Week Wise'), ('SqFt', 'Per SqFt per Day')], max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True, help_text='0-not available, 1-available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.category')),
            ],
        ),
    ]
